name: VCH Update Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Split Changelog
        id: changelog
        run: |
          # Read the changelog and split by sections using "---" as delimiter
          
          # Part 1: Header and Latest Updates (up to first ---)
          echo "part1<<EOF" >> $GITHUB_OUTPUT
          awk '/^---$/{if(count==0){count++; print; next} else {exit}} {print}' CHANGELOG.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          # Part 2: Version 1.0 section (between first and second ---)
          echo "part2<<EOF" >> $GITHUB_OUTPUT
          awk '/^---$/{if(count==0){count++; next} else if(count==1){count++; exit} else {next}} count>=1 {print}' CHANGELOG.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          # Part 3: Help section (after second ---)
          echo "part3<<EOF" >> $GITHUB_OUTPUT
          awk '/^---$/{if(count<2){count++; next} else {found=1; next}} found==1 {print}' CHANGELOG.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        
      - name: Send Changelog Part 1 to Discord
        if: success()
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            **📋 VCH Changelog (Part 1/3)**
            ${{ steps.changelog.outputs.part1 }}
            
      - name: Send Changelog Part 2 to Discord
        if: success() && steps.changelog.outputs.part2 != ''
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            **📋 VCH Changelog (Part 2/3)**
            ${{ steps.changelog.outputs.part2 }}
            
      - name: Send Changelog Part 3 to Discord
        if: success() && steps.changelog.outputs.part3 != ''
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            **📋 VCH Changelog (Part 3/3)**
            ${{ steps.changelog.outputs.part3 }}