name: VCH Update Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Split Changelog Dynamically
        id: changelog
        run: |
          # Split changelog by "---" sections dynamically
          
          # Create a temporary file with section markers
          awk 'BEGIN{section=0} /^---$/{section++; print "SECTION_SPLIT_" section; next} {print}' CHANGELOG.md > /tmp/changelog_split.txt
          
          # Count total sections
          TOTAL_SECTIONS=$(grep -c "SECTION_SPLIT_" /tmp/changelog_split.txt || echo "0")
          TOTAL_SECTIONS=$((TOTAL_SECTIONS + 1))  # Add 1 for the first section before any ---
          
          echo "total_sections=$TOTAL_SECTIONS" >> $GITHUB_OUTPUT
          
          # Split into individual sections
          current_section=0
          current_content=""
          
          while IFS= read -r line; do
            if [[ $line == SECTION_SPLIT_* ]]; then
              # Save current section if it has content
              if [[ -n "$current_content" ]]; then
                echo "section_${current_section}<<EOF" >> $GITHUB_OUTPUT
                echo "$current_content" >> $GITHUB_OUTPUT
                echo "EOF" >> $GITHUB_OUTPUT
              fi
              current_section=$((current_section + 1))
              current_content=""
            else
              if [[ -n "$current_content" ]]; then
                current_content="$current_content"$'\n'"$line"
              else
                current_content="$line"
              fi
            fi
          done < /tmp/changelog_split.txt
          
          # Save the last section
          if [[ -n "$current_content" ]]; then
            echo "section_${current_section}<<EOF" >> $GITHUB_OUTPUT
            echo "$current_content" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
          
          # Clean up
          rm -f /tmp/changelog_split.txt
        
      - name: Send Changelog Sections to Discord
        if: success()
        run: |
          TOTAL_SECTIONS="${{ steps.changelog.outputs.total_sections }}"
          
          for i in $(seq 0 $((TOTAL_SECTIONS - 1))); do
            SECTION_VAR="section_${i}"
            SECTION_CONTENT=$(echo "${{ steps.changelog.outputs }}" | jq -r ".${SECTION_VAR}" 2>/dev/null || echo "")
            
            if [[ -n "$SECTION_CONTENT" && "$SECTION_CONTENT" != "null" ]]; then
              # Send to Discord using curl
              curl -H "Content-Type: application/json" \
                   -X POST \
                   -d "{\"content\": $(echo "$SECTION_CONTENT" | jq -Rs .)}" \
                   "${{ secrets.DISCORD_WEBHOOK }}"
              
              # Add small delay between messages
              sleep 2
            fi
          done