name: VCH Update Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Read Changelog
        id: changelog
        run: |
          # Read the changelog content with proper formatting preserved
          CHANGELOG_CONTENT=$(cat CHANGELOG.md)
          
          # Truncate if too long for Discord (Discord has a 2000 character limit per message)
          # We'll take the first 1900 characters and add a clean truncation message
          if [ ${#CHANGELOG_CONTENT} -gt 1900 ]; then
            CHANGELOG_CONTENT="${CHANGELOG_CONTENT:0:1900}"$'\n\n... *(message truncated due to Discord length limits)*'
          fi
          
          # Use GitHub's multiline output format to preserve formatting
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        
      - name: Send Changelog to Discord
        if: success()
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            ${{ steps.changelog.outputs.content }}